### ISSUE TITLE
RuntimeError after Host & Container apt-upgrade

### ISSUE THREAD

**Issue by ralfbgithub** [matiasdelellis/facerecognition-external-model#18]
Hello,

after apt-upgrade on the host and in the nextcloud docker container the following error below occurs:

Updating the facerecognition-external container also, or re-build, did not eliminate the error

RuntimeError: 

Error detected at line 111.
Error detected in file /tmp/pip-wheel-ho26inp5/dlib_3890393138614d1f83bcc5be40c3cb62/dlib/../dlib/python/numpy_image.h.
Error detected in function dlib::assert_is_image<rgb_pixel>(const pybind11::array&)::<lambda(char, size_t)>.

Failing expression was false.
unknown type

172.24.0.1 - - [30/Jun/2024 18:23:25] "POST /detect HTTP/1.1" 500 -
[2024-06-30 18:23:27,940] ERROR in app: Exception on /detect [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/facerecognition-external-model.py", line 140, in decorated_function
    return view_function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/facerecognition-external-model.py", line 156, in detect_faces
    img: numpy.ndarray = dlib.load_rgb_image(image_path)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
++++++++++++++++

response on occ face:background_job:  Faces found: 0. Image will be skipped because of the following error: External model response /detect with error

+

latest updates on the host:
base-files/stable 12.4+deb12u6 arm64 [upgradable from: 12.4+deb12u5]
bash/stable 5.2.15-2+b7 arm64 [upgradable from: 5.2.15-2+b2]
curl/stable 7.88.1-10+deb12u6 arm64 [upgradable from: 7.88.1-10+deb12u5]
libcjson1/stable 1.7.15-1+deb12u1 arm64 [upgradable from: 1.7.15-1]
libcurl3-gnutls/stable 7.88.1-10+deb12u6 arm64 [upgradable from: 7.88.1-10+deb12u5]
libcurl4/stable 7.88.1-10+deb12u6 arm64 [upgradable from: 7.88.1-10+deb12u5]
libfreetype6/stable 2.12.1+dfsg-5+deb12u3 arm64 [upgradable from: 2.12.1+dfsg-5]
libgdk-pixbuf-2.0-0/stable 2.42.10+dfsg-1+deb12u1 arm64 [upgradable from: 2.42.10+dfsg-1+b1]
libgdk-pixbuf2.0-bin/stable 2.42.10+dfsg-1+deb12u1 arm64 [upgradable from: 2.42.10+dfsg-1+b1]
libgdk-pixbuf2.0-common/stable 2.42.10+dfsg-1+deb12u1 all [upgradable from: 2.42.10+dfsg-1]
libglib2.0-0/stable 2.74.6-2+deb12u3 arm64 [upgradable from: 2.74.6-2+deb12u2]
libglib2.0-bin/stable 2.74.6-2+deb12u3 arm64 [upgradable from: 2.74.6-2+deb12u2]
libglib2.0-data/stable 2.74.6-2+deb12u3 all [upgradable from: 2.74.6-2+deb12u2]
libglib2.0-dev-bin/stable 2.74.6-2+deb12u3 arm64 [upgradable from: 2.74.6-2+deb12u2]
libglib2.0-dev/stable 2.74.6-2+deb12u3 arm64 [upgradable from: 2.74.6-2+deb12u2]
libgnutls30/stable 3.7.9-2+deb12u3 arm64 [upgradable from: 3.7.9-2+deb12u2]
libltdl7/stable 2.4.7-7~deb12u1 arm64 [upgradable from: 2.4.7-5]
libpq5/stable 15.7-0+deb12u1 arm64 [upgradable from: 15.6-0+deb12u1]
libpython3.11-minimal/stable 3.11.2-6+deb12u2 arm64 [upgradable from: 3.11.2-6]
libpython3.11-stdlib/stable 3.11.2-6+deb12u2 arm64 [upgradable from: 3.11.2-6]
libseccomp2/stable 2.5.4-1+deb12u1 arm64 [upgradable from: 2.5.4-1+b3]
libssl3/stable 3.0.13-1~deb12u1 arm64 [upgradable from: 3.0.11-1~deb12u2]
libsystemd0/stable 252.26-1~deb12u2 arm64 [upgradable from: 252.22-1~deb12u1]
libudev1/stable 252.26-1~deb12u2 arm64 [upgradable from: 252.22-1~deb12u1]
linux-libc-dev/stable 6.1.94-1 arm64 [upgradable from: 6.1.90-1]
openssl/stable 3.0.13-1~deb12u1 arm64 [upgradable from: 3.0.11-1~deb12u2]
python3.11-minimal/stable 3.11.2-6+deb12u2 arm64 [upgradable from: 3.11.2-6]
python3.11/stable 3.11.2-6+deb12u2 arm64 [upgradable from: 3.11.2-6]
++++++++

I am grateful for any advice

Ralf

**Comment by ralfbgithub** [comment]
new container and "suddenly" it's working again😮
please excuse any inconvenience caused
